# Arrays bidimensionales con Numpy

## Datos multidimensionales

Podemos hacerlo de varias formas, una de ellas es una lista de listas.

In [2]:
import numpy as np
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print (m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Podemos obtener la dimensión de un array multidimensional con <code>shape</code>, y el número de dimensiones con <code>ndim</code>.

In [4]:
print (m.shape)
print (m.ndim)

(3, 4)
2


Podemos crear matrices con el  **shape** que necesitemos.

In [12]:
ones = np.ones((3, 7))
print (ones)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Podemos usar las mismas funciones en los arrays multidimensionales y en los unidimensionales.

In [13]:
ones.fill(2)
print (ones.sum())
print (ones)

42.0
[[2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2.]]


## Índices y subconjuntos

Un índice simple nos permite obtener un registro, un índice múltiple nos permite obtener un dato.

In [8]:
print (m[2])
print (m[2][2])
print (m[2,2])

[ 9 10 11 12]
11
11


Podemos particionar el array usando los índices.

In [15]:
# Las columnas 6 y 7 serán reemplazadas con el valor 10
ones[:,5:7].fill(10)
print (ones)

[[ 2.  2.  2.  2.  2. 10. 10.]
 [ 2.  2.  2.  2.  2. 10. 10.]
 [ 2.  2.  2.  2.  2. 10. 10.]]


In [18]:
# A partir de la tercera columna multiplicamos por 10.
m[:, 2] = m[:,2]*10
print (m)

# El segundo registro será todo 0
m[1,:] = 0
print (m)

[[   1    2  300    4]
 [   0    0    0    0]
 [   9   10 1100   12]]
[[   1    2  300    4]
 [   0    0    0    0]
 [   9   10 1100   12]]


Del mismo modo podemos trabajar con matrices booleanas.

In [21]:
#Matriz booleana donde el valor verdadero será el valor mayor de 10 en la matriz
print(m)
sel = m >10 
print (sel)

# Obtenemos un array con todos aquellos elementos de la matriz que son falsos.
a = m[sel == False]
print (a)

[[   1    2  300    4]
 [   0    0    0    0]
 [   9   10 1100   12]]
[[False False  True False]
 [False False False False]
 [False False  True  True]]
[ 1  2  4  0  0  0  0  9 10]


## Operando en distintos índices

Las operaciones matriciales estadísticas se llevan a cabo por **índice**.

In [23]:
#Array de 18 elementos con números enteros aleatorios entre el 1 y el 20
mat = np.random.randint(1, 20, 18)
mat

array([15,  5,  7, 13, 19,  5, 13,  1,  5, 11, 15, 11, 10,  1, 13, 16, 18,
       12])

In [25]:
#Transformamos el array en una matriz de 6 filas x 3 columnas
mat = mat.reshape((6,3))
mat

array([[15,  5,  7],
       [13, 19,  5],
       [13,  1,  5],
       [11, 15, 11],
       [10,  1, 13],
       [16, 18, 12]])

In [26]:
mat.sum()

190

Sumamos las 6 filas (fila axis=1)

In [27]:
mat.sum(axis=1)

array([27, 37, 19, 37, 24, 46])

Sumamos las 3 columnas (axis=0)

In [29]:
mat.sum(axis=0)

array([78, 59, 53])

## Transposición 

NumPy arrays can be reshaped easily.

In [33]:
#array 15 números entre 20 y 30
m1 = np.linspace(20,30, 15)
print (m1.shape)

#Transformamos el array en matriz
m1 = m1.reshape((5, 3)) # You have to pass a tuple
print (m1)
print (m1.shape)

(15,)
[[20.         20.71428571 21.42857143]
 [22.14285714 22.85714286 23.57142857]
 [24.28571429 25.         25.71428571]
 [26.42857143 27.14285714 27.85714286]
 [28.57142857 29.28571429 30.        ]]
(5, 3)


Transposición de matrices.

In [35]:
print (m1.T)

[[20.         22.14285714 24.28571429 26.42857143 28.57142857]
 [20.71428571 22.85714286 25.         27.14285714 29.28571429]
 [21.42857143 23.57142857 25.71428571 27.85714286 30.        ]]
